config/routes.rb
Rails.application.routes.draw do

  devise_for :managers
  devise_for :people
  mount IncidentV1::GrapeAPI => '/v1'
  resources :incidents
  root "incidents#index"

  namespace :dashboard do
    namespace :admin do
      resources :people
      resources :incidents
      resources :cates
    end  
  end

  resources :conversations do
    resources :messages
  end
   
  get "/update_group" => "incidents#update_group"
  get "/update_incident" => "incidents#update_incident"
  get "/index" => "incidents#index"
  get 'apidoc/menu'
  get 'apidoc/overview'
  get 'apidoc/start'
  get 'apidoc/sample'
  get 'apidoc/reference'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'Person'
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'Person'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, :scope => :recipient_id

	scope :involving, -> (person) do
		where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
	end

	scope :between, -> (sender_id,recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    #@messages = @conversation.messages

    @arr = Message.where(:id=>0)
    
    $redis.zrangebyscore("conversation_"+params[:conversation_id].to_s ,0,(Time.now.to_f * 1).to_i , {withscores: true}).each do |source|
      mes = source[0]
      new_m = JSON.load mes
      @arr << Message.new(new_m)
    end  
    @messages = @arr

    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_person == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="glyphicon glyphicon-comment"></i>

    <h1>Chat with: <%= @reciever.user_name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='glyphicon glyphicon-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='glyphicon glyphicon-remove'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
      <div class="chat-form-btns">    
         <%= f.submit "send", class: "btn btn-primary btn-sm btn-submit"%>

    </div>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>