config/routes.rb
Rails.application.routes.draw do

  devise_for :managers
  devise_for :people
  mount IncidentV1::GrapeAPI => '/v1'
  resources :incidents
  root "incidents#index"

  namespace :dashboard do
    namespace :admin do
      resources :people
      resources :incidents
      resources :cates
    end  
  end

  resources :conversations do
    resources :messages
  end
   
  get "/update_group" => "incidents#update_group"
  get "/update_incident" => "incidents#update_incident"
  get "/index" => "incidents#index"
  get 'apidoc/menu'
  get 'apidoc/overview'
  get 'apidoc/start'
  get 'apidoc/sample'
  get 'apidoc/reference'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
  belongs_to :status  
  belongs_to :cate
  belongs_to :reporter, :class_name => "Person", :foreign_key => :reporter_id
  belongs_to :assignee, :class_name => "Person", :foreign_key => :assignee_id
  validates :location, :severity, :cate_id, :reporter_id, presence: true
  validates :other_cate_description, presence: true, :if => :other_cate?
  
  validates :cate, :status, :reporter, presence: true
  has_attached_file :cover ,
    styles: {
      originial: "1024x1024>",
      cover: "300x300>",
      icon:  "150x150#"
    },
    s3_headers: {
      'Cache-Control' => 'max-age=315576000', 
      'Expires' => 10.years.from_now.httpdate
    },
    default_url: "/images/missing.png"
    
    validates_attachment_content_type :cover , content_type: /\Aimage\/.*\Z/


  def other_cate?
    if cate_id != nil
      if Cate.last != nil
        return cate_id == Cate.last.id
      end
    end
    return false
  end
  
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    #@incidents = @paginate = Incident.includes(:cate).order('id DESC').paginate(:page => params[:page], :per_page => 5)
    #incidents = Incident.where("created_at > ?", Time.at(params[:after].to_i + 1)).order('id DESC').paginate(:page => params[:page], :per_page => 5)
    
    after = params[:after].to_i
    if (after == 0)
      @incidents = Incident.all.order('id DESC')
    end  
    @added = $redis.zrangebyscore("incidents" , after + 1 , (Time.now.to_f * 1).to_i , {withscores: true}).length 
    num = 0
     $redis.zrangebyscore("incidents" , after + 1 , (Time.now.to_f * 1).to_i , {withscores: true}).each do |s|
         inc = s[0]
         new_i = JSON.load inc
          if new_i['severity'] == 1
           num = num +1
       end  
    end
     @emergency_num = num
  end

  def update_group 
    @group = $redis.hget('people_group', params[:reporter_id])
    @department = $redis.hget('group_department', @group)
    @phone = $redis.hget('phone', params[:reporter_id])
    @email = $redis.hget('email', params[:reporter_id])
  end

  def update_incident 
    after = params[:after].to_i
    if (after == 0)
      @incidents = Incident.all.order('id DESC')
    end  
    @arr = []
    $redis.zrangebyscore("incidents" , after + 1 , (Time.now.to_f * 1).to_i , {withscores: true}).each do |source|
      inc = source[0]
      new_i = JSON.load inc
      @arr << Incident.new(new_i)
    end  
    @incidents  = Incident.where(id: @arr.map(&:id)).order('id DESC')  
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)
    @incident.reporter_id = current_person.id
    respond_to do |format|
      if @incident.save
        inc = @incident.to_json
        $redis.zadd('incidents', @incident.created_at.to_i, inc)
        format.html { redirect_to :action => :index}
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    @incident = Incident.find(params[:id])
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to :action => :index}
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    redirect_to :action => :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit!
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_incident.html.erb
      <% if incident.status_id < 3%>
      <li class="incident" data-time="<%= incident.created_at.to_i %>"> 
        <% puts case incident.status_id%>
          <%when 1%>
            <div class="timeline-badge primary" style="position:relative; z-index:1;"><span class="glyphicon glyphicon-bullhorn"></span></div>
          <%when 2%>
            <div class="timeline-badge warning" style="position:relative; z-index:1;"><span class="glyphicon glyphicon-eye-open"></span></div>
          <% end %>
        
        <div class="timeline-panel" data-time="<%= incident.created_at.to_i %>">
          <div class="timeline-heading">
            <div style="width:95%"> 
            <h4 class="timeline-title" style="word-break:break-all">Location: <%= incident.location %></h4>
            </div>
            <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i>Report at: <%= incident.created_at %></small></p>
          </div>

          <div>
            <% puts case incident.severity%>
              <%when 1%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,50,0,0.9) ">
              <%when 2%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,102,0,0.7)">
              <%when 3%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,255,0,0.5)">
              <%when 4%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(0,158,255,0.3)">
              <%when 5%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(0,255,0,0.1)">
            <% end %>
              <b>Severity: </b><%= incident.severity %><br>
              <b>Category: </b><%= $redis.hget('cates', incident.cate_id) %><br>
              <b>Reporter: </b><%= $redis.hget('people', incident.reporter_id) %> <br>
              <b>Status:</b>
              <% puts case incident.status_id%>
                <%when 1%>
                  <font color="blue"><b><%= $redis.hget('statuses', incident.status_id) %></b></font>
                <%when 2%>
                  <font color="orange"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <%when 3%>
                  <font color="green"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <%when 4%>
                  <font color="gray"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <% end %><br>
               </div> 
              
              <div style="float: left; width: 40%">
                <center style="width: 100%"> <%= image_tag incident.cover.url(:icon), :width => "50%", :height => "50%"%> </center>
              </div>  
          </div>

            <div style="padding-top:10px;float: left;width: 100%"></div>
            <div style="float: left;width: 100%">
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          incident_path(incident), :class => 'btn btn-info btn-xs'%>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_incident_path(incident), :class => 'btn btn-primary btn-xs' %>
            </div>

        </div>
      </li>
      <% else %>
      <li class="timeline-inverted">
        <% puts case incident.status_id%>
          <%when 3%>
            <div class="timeline-badge success" style="position:relative; z-index:1;"><span class="glyphicon glyphicon-check"></span></div>
          <%when 4%>
            <div class="timeline-badge" style="position:relative; z-index:1;"><span class="glyphicon glyphicon-ban-circle"></span></div>      
          <% end %>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <div style="width:95%"> 
            <h4 class="timeline-title" style="word-break:break-all">Location: <%= incident.location %></h4>
          </div>
          <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i>Report date and time:<%= incident.created_at %></small></p>
        </div>
       <div>
            <% puts case incident.severity%>
              <%when 1%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,50,0,0.9) ">
              <%when 2%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,102,0,0.7)">
              <%when 3%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(255,255,0,0.5)">
              <%when 4%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(0,158,255,0.3)">
              <%when 5%>
                <div class="timeline-body" style="float: left; width: 60%;background-color:rgba(0,255,0,0.1)">
            <% end %>
              <b>Severity: </b><%= incident.severity %><br>
              <b>Category: </b><%= $redis.hget('cates', incident.cate_id) %><br>
              <b>Reporter: </b><%= $redis.hget('people', incident.reporter_id) %> <br>
              <b>Status:</b>
              <% puts case incident.status_id%>
                <%when 1%>
                  <font color="blue"><b><%= $redis.hget('statuses', incident.status_id) %></b></font>
                <%when 2%>
                  <font color="orange"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <%when 3%>
                  <font color="green"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <%when 4%>
                  <font color="gray"><b><%= $redis.hget('statuses', incident.status_id)%></b></font>
                <% end %><br>
               </div> 
              
              <div style="float: left; width: 40%">
                <center style="width: 100%"> <%= image_tag incident.cover.url(:icon), :width => "50%", :height => "50%"%> </center>
              </div>  
          </div>

            <div style="padding-top:10px;float: left;width: 100%"></div>
            <div style="float: left;width: 100%">
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          incident_path(incident), :class => 'btn btn-info btn-xs'%>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_incident_path(incident), :class => 'btn btn-primary btn-xs' %>
            </div>

        </div>
    </li>
      <% end %>

app/views/incidents/edit.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/incidents/index.html.erb
<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  <div class="page-header">
    <h1>Timeline of Incidents</h1>
  </div>


  <div class="row">
    <div style="float: left; width: 50%; height: 100%;">
      <div style="margin-left: 5%; float: left;"> 
        <button class="btn btn-primary" type="button">
          Total Reported Incidents:<span id="reported" class="badge"><%= Incident.where(:status => 1).count%></span>
        </button>   
      </div>

      <div style="margin-left: 5%;float: left;"> 
        <button class="btn btn-danger" type="button">
          Total Processing Incidents:<span id="processing" class="badge"><%= Incident.where(:status => 2).count%></span>
        </button>
      </div>

    </div>

    <div style="float: left; width: 50%; height: 100%;">
      <div style="margin-left: 5%;float: left;"> 
        <button class="btn btn-success" type="button">
          Total Solved Incidents:<span id="solved" class="badge"><%= Incident.where(:status => 3).count%></span>
        </button>   
      </div>

      <div style="margin-left: 5%;float: left;"> 
        <button class="btn btn-default" type="button">
          Total Closed Incidents:<span id="closed" class="badge"><%= Incident.where(:status => 4).count%></span>
        </button>
      </div>
    </div>





  </div>
 
 <p id="show_incidents" style="display: none">
    New incidents have been posted. <a href="#">Show Incidents</a>
 </p>

  <ul class="timeline">
    <%= render @incidents %>
  </ul>
  
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script type="text/javascript">
var wait = 1000;
var minWait = 1000;
var maxWait = 20000;
var changeMode = 1; // 1 binary, 2 increment
var direction = 1; // 1 increase, -1 decrease

  $(function() {
    //console.log($(".timeline").is(':visible'));
    //console.log($("#groupDiv").is(':visible'));

    if($(".timeline").is(':visible')) {
      //console.log("in function");
      setTimeout(updateIncidents, 10000);
    } 
});

function updateIncidents () {
  if($(".timeline").is(':visible')) {
    if ($(".timeline").children().length > 0) {
        var after = $(".timeline").children().first().attr("data-time");
    } else {
        var after = "0";
    }
    //console.log(after);
    $.getScript("/incidents.js?after=" + after)
    //console.log("<%= $redis.hget('new_incidents','number').to_i%>");
    console.log(wait);
    setTimeout(updateIncidents,wait)
  }
}

$("#show_incidents a").click(function()
  {
    $.ajax({
      url:"<%= update_incident_path %>", 
      data:{after:$(".timeline").children().first().attr("data-time")},
      dataType:"script"
    })
  })
</script>

app/views/incidents/index.js.erb
if (changeMode == 1) {
    <% if (@added>0) %> {
      wait = Math.max(minWait, wait / 2);
      if (direction == 1) {
        direction = -1;
        changeMode = 2;
      }
    }
    <% else %> {
      wait = Math.min(maxWait, wait * 2); 
      if (direction == -1) {
        direction = 1;
        changeMode = 2;
      }  
    }
    <% end %>
}
else {
	<% if (@added>0) %> {
	  wait = Math.max(minWait, wait - 5000);
	  if (direction == -1) {
	    changeMode = 1;
	  }
	  else {
	    direction = -1;
	  }
	}
	<% else %> {
	  wait = Math.max(minWait, wait + 5000);
	  if (direction == 1) {
	    changeMode = 1;
	  }
	  else {
	    direction = 1;
	  }
	}
	<% end %>
}

<% if (@added>0) %>
	if($("#show_incidents").is(":hidden")) {
		//console.log("in index.js.erb")
		$("#show_incidents").show();  

		//<% $redis.hset('new_incidents', 'number', 2) %>
		//console.log("<%= $redis.hget('new_incidents','number').to_i%>");

		var old = $("#reported").text();
		//console.log(old);
		var current = Number(old) + Number("<%= @added %>");
		$("#reported").text(current);
		<%if (@emergency_num > 0)%>
			<% conversation_id = Conversation.where(:recipient_id =>Person.first.id,:sender_id => current_person.id).first.id%>
			var id = <%=  conversation_id%>
			var chatbox = $("#chatbox_" + id + " .chatboxcontent");
			<% new_body = "Alert! Critical Incident(s) created! " %>
			<% new_message = Message.new(:body=>new_body,:person_id=>Person.first.id,:conversation_id=>conversation_id,:created_at=>DateTime.now) %>
			chatbox.append("<%= raw escape_javascript(render(new_message)) %>");
			chatBox.notify();
			chatbox.scrollTop(chatbox[0].scrollHeight);
		<% end %>
	}


<% end %>

app/views/incidents/new.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/incidents/show.html.erb
<%- model_class = Incident -%>
<div class="page-header" style = "margin-left: 5%;">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class = "row">
  <div style="float: left; width: 30%;">
    <center style="width: 100%"> <%= image_tag @incident.cover.url(:icon), :width => "50%", :height => "50%"%> </center>
  </div>

  <div style="float: left; width: 70%;">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
      <dd style="word-break:break-all"><%= @incident.location %></dd>
      <dt><strong><%= model_class.human_attribute_name(:status_id) %>:</strong></dt>
      <dd><%= @incident.status.status_name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:report_date_time) %>:</strong></dt>
      <dd><%= @incident.created_at %></dd>
      <dt><strong><%= model_class.human_attribute_name(:processed_date_time) %>:</strong></dt>
      <dd><%if @incident.processed_date_time == nil %>
          Not available
          <%else%>
          <%= @incident.processed_date_time%> 
          <%end%>
      </dd>
      <dt><strong><%= model_class.human_attribute_name(:solved_date_time) %>:</strong></dt>
      <dd><%if @incident.solved_date_time == nil %>
          Not available
          <%else%>
          <%= @incident.solved_date_time%> 
          <%end%></dd>
      <dt><strong><%= model_class.human_attribute_name(:closed_date_time) %>:</strong></dt>
      <dd><%if @incident.closed_date_time == nil %>
          Not available
          <%else%>
          <%= @incident.closed_date_time%> 
          <%end%></dd>
      <dt><strong><%= model_class.human_attribute_name(:severity) %>:</strong></dt>
      <dd><%= @incident.severity %></dd>
      <dt><strong>Category:</strong></dt>
      <dd><%= @incident.cate.cate_name %></dd>
      <dt><strong>Other category</strong>:</dt>
      <dd style="word-break:break-all"><%if @incident.other_cate_description == nil %>
          Not available
          <%else%>
          <%= @incident.other_cate_description%> 
          <%end%></dd>
      <dt><strong><%= model_class.human_attribute_name(:incident_description) %>:</strong></dt>
      <dd style="word-break:break-all"><%if @incident.incident_description == "" %>
          Not available
          <%else%>
          <%= @incident.incident_description%> 
          <%end%></dd>
      <dt><strong>Reporter:</strong></dt>
      <dd><%= @incident.reporter.user_name %></dd>
      <dt><strong>Assignee:</strong></dt>
      <dd><%if @incident.assignee_id == nil %>
          Not available
          <%else%>
          <%= @incident.assignee.user_name%> 
          <%end%></dd>
    </dl>
  </div>
</div>

<div style="margin-left: 5%;">
  <%= link_to t('.back', :default => t("helpers.links.back")),
                incidents_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_incident_path(@incident), :class => 'btn btn-default' %>
</div>

app/views/incidents/update_group.js.erb
$('#groupDiv').val("<%= escape_javascript(@group) %>");
$('#departmentDiv').val("<%= escape_javascript(@department) %>");
$('#phoneDiv').val("<%= escape_javascript(@phone) %>");
$('#emailDiv').val("<%= escape_javascript(@email) %>");

app/views/incidents/update_incident.js.erb
$(".timeline").prepend("<%=raw escape_javascript(render(@incidents)) %>");
  //console.log("render complete");
$("#show_incidents").hide();
//<% $redis.hset('new_incidents', 'number', 1)%>
//console.log("in on click");
//console.log("<%= $redis.hget('new_incidents','number').to_i%>");