config/routes.rb
Rails.application.routes.draw do

  devise_for :managers
  devise_for :people
  mount IncidentV1::GrapeAPI => '/v1'
  resources :incidents
  root "incidents#index"

  namespace :dashboard do
    namespace :admin do
      resources :people
      resources :incidents
      resources :cates
    end  
  end

  resources :conversations do
    resources :messages
  end
   
  get "/update_group" => "incidents#update_group"
  get "/update_incident" => "incidents#update_incident"
  get "/index" => "incidents#index"
  get 'apidoc/menu'
  get 'apidoc/overview'
  get 'apidoc/start'
  get 'apidoc/sample'
  get 'apidoc/reference'

end

app/controllers/apidoc_controller.rb
class ApidocController < ApplicationController
  
  def menu
  end

  def overview
  end

  def start
  end

  def sample
  end
  
  def reference
  end

end

app/views/apidoc/menu.html.erb
<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  <div class="page-header">
    <h1>API DOCS</h1>
  </div>

  <div> 

    <p>
    <%= link_to "API Document", apidoc_menu_path %>
    </p>



      <button class="btn btn-primary" type="button" style="margin: 1%; width: 400px;">
        <div class="img" style="margin: 4%; width: 18%; float:left">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54.7 65.9" enable-background="new 0 0 54.7 65.9">
              <path fill="#fff" d="M27.4 65.9c-15.1 0-27.4-12.2-27.4-27.3 0-15.1 12.3-27.4 27.4-27.4 15.1 0 27.4 12.3 27.4 27.4-.1 15.1-12.3 27.3-27.4 27.3zm0-53.7c-14.6 0-26.4 11.8-26.4 26.4 0 14.5 11.8 26.4 26.4 26.4 14.5 0 26.4-11.8 26.4-26.4-.1-14.6-11.9-26.4-26.4-26.4zm-7.9-12.2h15.7v1h-15.7zm31.151 14.254l.707.707-4.808 4.808-.707-.707zm-19.451-2.354h-1v-10.9h-5.7v10.9h-1v-11.9h7.7zm18.745.952l2.829 2.828-.707.707-2.829-2.828zm-35.376 12.699l12.728 12.728-.707.707-12.728-12.728z"></path>
            </svg>
        </div>
        <div style="margin: 10%;width: 90%;"> 
          <span class="badge" style="margin: 1%"><h4><%= link_to "Overview", apidoc_overview_path %></h4></span>
        </div>
        <p style="word-break: break-all"> The description and advantages of our API</p>
      </button>    

      <button class="btn btn-danger" type="button" style="margin: 1%; width: 400px;">
        <div class="img" style="margin: 4%; width: 18%; float:left">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 59.7 70.8" enable-background="new 0 0 59.7 70.8">
              <path fill="#fff" d="M59.7 70.8h-59.7v-70.8h59.7v70.8zm-58.7-1h57.7v-68.8h-57.7v68.8zm21.8-47.5h25.6v1h-25.6zm0 14.8h25.6v1h-25.6zm0 14.9h25.6v1h-25.6zm-13.4-30l-2.6-2.6.7-.7 1.9 1.9 7.1-7.1.7.7zm0 14.9l-2.6-2.7.7-.7 1.9 2 7.1-7.1.7.7z"></path>
            </svg>
        </div>
        <div style="margin: 10%;width: 90%;"> 
          <span class="badge" style="margin: 1%"> <h4><%= link_to "Getting Started", apidoc_start_path %></h4> </span>
        </div>
        <p style="word-break:break-all"> A set of simple tutorials with examples on how to use our API</p>
      </button>  
 
      <button class="btn btn-success" type="button" style="margin: 1%; width: 400px;">
        <div class="img" style="margin: 4%; width: 18%; float:left">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" enable-background="new 0 0 80 80"><path fill="#fff" d="M16.27 54.9l-15.2-15.2 15.2-15.2.71.71-14.49 14.49 14.49 14.49zm48.24 0l-.71-.71 14.49-14.49-14.49-14.49.71-.71 15.2 15.2zm-9.293-41.262l.863.506-30.284 51.621-.863-.506z"></path></svg>
        </div>
        <div style="margin: 10%;width: 90%;"> 
          <span class="badge" style="margin: 1%"> <h4><%= link_to "Sample Code", apidoc_sample_path %></h4> </span> 
        </div>
        <p style="word-break: break-all">The sample code demonstrates how to make a REST request <br>in different languages.</p>
      </button>    
  
      <button class="btn btn-warning" type="button" style="margin: 1%; width: 400px;">
        <div class="img" style="margin: 4%; width: 18%; float:left">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 77.07 68.74" enable-background="new 0 0 77.07 68.74"><path fill="#fff" d="M31.95 68.74l-.23-.11-31.72-15.86v-48.27l31.95 14.75 31.95-14.75v10.08h-1v-8.51l-30.95 14.28-30.95-14.28v46.08l30.95 15.47 30.95-15.47v-5.75h1v6.37zm0-55.64l-24.42-12.21.45-.89 23.97 11.98 23.96-11.98.45.89z"></path><path d="M31.95 68.18m0-48.38" stroke="#fff" stroke-miterlimit="10" fill="none"></path><path d="M63.4 44.22c-7.54 0-13.68-6.14-13.68-13.68s6.14-13.68 13.68-13.68 13.67 6.14 13.67 13.69c0 7.54-6.13 13.67-13.67 13.67zm0-26.35c-6.99 0-12.68 5.69-12.68 12.68s5.68 12.67 12.68 12.67 12.68-5.69 12.68-12.68-5.69-12.67-12.68-12.67zm-.58 6.16h1v13.09h-1zm-6.04 6.04h13.09v1h-13.09zm-19.83-12.81h1v48.29h-1zm-11.05 0h1v48.29h-1z" fill="#fff"></path></svg>
        </div>
        <div style="margin: 10%;width: 90%;"> 
          <span class="badge" style="margin: 1%"><h4><%= link_to "Reference Material", apidoc_reference_path %></h4></span>
        </div>    
        <p style="word-break: break-all">Provide detailed information about each class </p>
        <br>     
      </button> 
  </div>
</div>

app/views/apidoc/overview.html.erb
<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  	<div class="page-header">
    	<h1>API DOCS: 
    		Overview</h1>
  	</div>

  	<div> 
		<p> This Application Protocol Interface (API) was created by the Tufts University Comp120 Team 8 for use by developers to build  website or application for reporting incidents. This user friendly interface provides several RESTful endpoints that allow for different actions on Incident and User class, including GET, POST, PUT and DELETE.</p>

		<h4> Grape </h4>
		<p>We used framework Grape to build our API.
		<p>Grape is a REST-like API micro-framework, which is built to easily and quickly produce APIs for Ruby-rooted web applications on top of Rack. It is a framework that is lightweight but still has out-of-the-box API support. Besides, getting started with Grape is as simple as installing the gem, creating an API class that inherits from Grape::API.</p>
		<p>Another reason we chose Grape instead of Rails::API is that the default configuration for Rails::API is 99% the same as Rails, chances are there’s a lot of cruft that’s included are not needed for a pure API. These extras are likely a lot of what is slowing Rails down.</p>

		<h4> Security </h4>
		<p> Authentication and authorization plan for each endpoint are shown in the Reference part. This will be implement in our next leg.</p>
		<p>Authentication: know who the user is and are his/her credentials valid.</p>
		<p>Authorization: provide access only to the incidents a particular logged-in user is authorized to modify/see.</p>
  	</div>

  	<%= link_to t('.back', :default => t("helpers.links.back")),
                apidoc_menu_path, :class => 'btn btn-default'  %>
</div>

app/views/apidoc/reference.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  	<div class="page-header">
    	<h1>API DOCS: Reference</h1>
  	</div>

  	<p> Base URL: http://comp120team8reporter.herokuapp.com/v1
  	<br>

  	<h4> Incident </h4>
  	<table class="table table-bordered table-hover">
	    <tr class="info">
	        <td>Method</td>
	        <td>Relative URL</td>
	        <td>Function</td>
	        <td>Required Params</td>
	        <td>Response/Status Code </td>
	        <td>Authentication and Authorization</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/incident/all</td>
	        <td>List all Incidents</td>
	        <td></td>
	        <td>200-success</td>
	        <td>Valid users can see the list of all incidents.</td>
	    </tr>
	    <tr class="active">
	        <td>DELETE</td>
	        <td>/incident/{id}</td>
	        <td>Delete an incident</td>
	        <td>id (integer)</td>
	        <td>200-success 404-incident not found</td>
	        <td>A user can only delete the incidents he/she reported. A manager can delete any incidents.</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/incident/{id}</td>
	        <td>Get incidents by id</td>
	        <td>id (integer)</td>
	        <td>200-success 400-incident not found</td>
	        <td>Valid users can search the incidents by id.</td>
	    </tr>
	    <tr class="active">
	        <td>PUT</td>
	        <td>/incident/{id}</td>
	        <td>Update an incident information</td>
	        <td>id (integer), location (string), severity (integer), cate_id (integer), reporter_id (integer)</td>
	        <td>200-success 409-invalid input</td>
	        <td>A user can only update the incidents he/she reported or assigned. A manager can update any incidents.</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/incident/incident_severity</td>
	        <td>Get incidents by severity</td>
	        <td>severity (integer)</td>
	        <td>200-success 400-incident not found</td>
	        <td>Valid users can search the incidents by severity.</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/incident/incident_cate_id</td>
	        <td>Get incidents by category</td>
	        <td>cate_id (integer)</td>
	        <td>200-success 400-incident not found</td>
	        <td>Valid users can search the incidents by category.</td>
	    </tr>
	    <tr class="active">
	        <td>POST</td>
	        <td>/incident/new</td>
	        <td>Creat an incident</td>
	        <td>location (string), severity (integer), cate_id (integer), reporter_id (integer)</td>
	        <td>200-success 409-invalid input</td>
	        <td>Valid users can create incidents.</td>
	    </tr>
	</table>
	<br>

	<h4> User </h4>
  	<table class="table table-bordered table-hover">
	    <tr class="info">
	        <td>Method</td>
	        <td>Relative URL</td>
	        <td>Function</td>
	        <td style="width:23%">Required Params</td>
	        <td>Response/Status Code </td>
	        <td style="width:20%">Authentication and Authorization</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/user/all</td>
	        <td>List all Users</td>
	        <td></td>
	        <td>200-success</td>
	        <td>Managers can see the list of all users.</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/user /user_reported_incidents</td>
	        <td>Get reported incidents by username</td>
	        <td>username (string)</td>
	        <td>200-success 400-user not found</td>
	        <td>Valid users can only search for the incidents reported by themselves. Managers can search for the incidents reported by any users.</td>
	    </tr>
	    <tr class="active">
	        <td>GET</td>
	        <td>/user /user_assigned_incidents</td>
	        <td>Get assigned incidents by username</td>
	        <td>username (string)</td>
	        <td>200-success 400-user not found</td>
	        <td>Valid users can only search for the incidents assigned to themselves. Managers can search for the incidents assigned to any users.</td>
	    </tr>
	    <tr class="active">
	        <td>POST</td>
	        <td>/user/new</td>
	        <td>User sign up</td>
	        <td>last_name (string), use_rname (string), phone<sup>*</sup> (string), emailphone<sup>**</sup> (string), group_id (integer), pwphone<sup>***</sup> (string)</td>
	        <td>200-success 409-conflict</td>
	        <td>Any potential users can create an account.</td>
	    </tr>
	    <tr class="active">
	        <td>PUT</td>
	        <td>/user/{id}</td>
	        <td>Update an user information</td>
	        <td>id (integer), last_name (string), user_name (string), phone<sup>*</sup> (string), email<sup>**</sup> (string), group_id (integer), pw<sup>***</sup> (string)</td>
	        <td>200-success 409-conflict</td>
	        <td>Valid users can only update their own information. Manages can update any users' information.</td>
	    </tr>
	</table>
	<p>* phone has to be in the correct form (numbers only or with '-' between the numbers or with (area code) before).</p>
	<p>** email has to be in the correct form (e.g. abc@def.ghi)</p>
	<p>*** pw has to be in the correct form (must be between 6 to 50 characters, must include and letters, numbers and may include special characters)</p>
	<br>

	<h4> Group </h4>
  	<table class="table table-bordered table-hover">
	    <tr class="info">
	        <td>Method</td>
	        <td>Relative URL</td>
	        <td>Function</td>
	        <td>Required Params</td>
	        <td>Response/Status Code </td>
	        <td>Authentication and Authorization</td>
	    </tr>	    
	    <tr class="active">
	        <td>GET</td>
	        <td>/group/{id}</td>
	        <td>Get group by id</td>
	        <td>id (integer)</td>
	        <td>200-success 400-group not found</td>
	        <td>Only for development use.</td>
	    </tr>
	</table>
	<br>

	<h4> Department </h4>
  	<table class="table table-bordered table-hover">
	    <tr class="info">
	        <td>Method</td>
	        <td style="width:20%">Relative URL</td>
	        <td style="width:18%">Function</td>
	        <td>Required Params</td>
	        <td>Response/Status Code </td>
	        <td>Authentication and Authorization</td>
	    </tr>	    
	    <tr class="active">
	        <td>GET</td>
	        <td>/department /groups_in_department</td>
	        <td>Get groups in a department by department name</td>
	        <td>department_name (string)</td>
	        <td>200-success 400-department not found</td>
	        <td>Only for development use.</td>
	    </tr>
	</table>
	<br>

	<h4> Category </h4>
  	<table class="table table-bordered table-hover">
	    <tr class="info">
	        <td>Method</td>
	        <td>Relative URL</td>
	        <td>Function</td>
	        <td>Required Params</td>
	        <td>Response/Status Code </td>
	        <td>Authentication and Authorization</td>
	    </tr>	    
	    <tr class="active">
	        <td>GET</td>
	        <td>/category/{id}</td>
	        <td>Get category by id</td>
	        <td>id (integer)</td>
	        <td>200-success 400-categary not found</td>
	        <td>Only for development use.</td>
	    </tr>
	</table>
	<br>

	<%= link_to t('.back', :default => t("helpers.links.back")),
                apidoc_menu_path, :class => 'btn btn-default'  %>
</div>

app/views/apidoc/sample.html.erb
<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  	<div class="page-header">
    	<h1>API DOCS: Sample Code</h1>
  	</div>

    <details>
    <summary>Java</summary>
    <script src="https://gist.github.com/leros/b039eb0f158268a0ced7.js"></script>
    </details>

    <details>
    <summary>Python</summary>
    <script src="https://gist.github.com/leros/f26277d06735cdcafe91.js"></script>
     </details>

    <br><br>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                apidoc_menu_path, :class => 'btn btn-default'  %>

</div>

app/views/apidoc/start.html.erb
<div class="container col-md-10 col-md-offset-1" style="background-image: url('/images/confectionary.png')">
  <div class="page-header">
    <h1>API DOCS: Getting Started</h1>
  </div>

  <div> 
      <p> These quickstarts are short, simple guides intended to help you get started using this API. </p>
      <br>

      <h4> Go to the API page </h4>
      <p> Click this <%= link_to "link", "http://comp120team8reporter.herokuapp.com/swagger"%> or the link at the footer of the home page or simple go to "http://comp120team8reporter.herokuapp.com/swagger"</p>
      <img src="/images/doc1.png" width="600" height="180" />
      <br><br>

      <h4> Choose a class </h4> 
      <p> For example: choose the Incident class by clicking 'incident', then operations about incidents will be shown.</p>
      <img src="/images/doc2.png" width="600" height="370" />
      <br><br>

      <h4> Choose a operation </h4> 
      <p> For example: choose the POST /incident/new, as it says this operation is used to create an incident.</p>
      <img src="/images/doc3.png" width="600" height="370" />
      <br><br>

      <h4> Get response </h4> 
      <p> Fill the form, choose response content type (now only JSON, more types will be added later) and click 'Try it out!' The response will be shown on the screen, including Curl, Request URL, Response Body, Response Code and Response Headers. If you need Request URL, for example, you can easily copy and paste it.</p>
      <img src="/images/doc4.png" width="600" height="350" />
      <br><br>

      <h4> Error Handle </h4> 
      <p> If a required parameter is missing, the field will change to red.</p>
      <img src="/images/doc5.png" width="300" height="18" />
      <p> If something wrong with the input, an error message will be return. For example, if we filled reprter_id with "foo" (which is a wrong type), the Response Body will return an error message "reporter_id is invalid" and the Response Code is 400.</p>
      <img src="/images/doc6.png" width="600" height="270" />


  </div>

  <%= link_to t('.back', :default => t("helpers.links.back")),
                apidoc_menu_path, :class => 'btn btn-default'  %>

</div>